file_up_down/urls.py
from django.conf.urls import url
from django.contrib import admin
from app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', views.login),
    url(r'^logout/', views.logout),
    url(r'^$',views.index),
    url(r'^upload/', views.receive),
    url(r'^download/', views.send),
]

app/models.py
from django.db import models

# Create your models here.
class Users(models.Model):
	user=models.CharField(max_length=10,unique=True)
	password=models.CharField(max_length=30)

app/views.py
# coding utf-8
from django.shortcuts import render,redirect

# Create your views here.
from django.http import HttpResponse

def index(request):
	if request.session.get('login_id'):
		user=request.session.get('login_id')
		loged_in=True
	else:
		user=''
		loged_in=False
	return render(request,'index.html',{'user':user,'loged_in':loged_in})

def login(request):
	if request.session.get('login_id'):
		return redirect('/')
	if request.method == 'POST':
		if request.session.get('login_id'):
			return redirect(request.META.get('HTTP_REFERER','/'))
		from app.models import Users
		user = request.POST.get('user')
		password = request.POST.get('password')
		if Users.objects.filter(user=user,password=password):
			request.session['login_id']=user
			return redirect(request.session['login_from'])
		else:
			return HttpResponse('账号或密码错误!')
	else:
		request.session['login_from']=request.META.get('HTTP_REFERER','/')
		return render(request,'login.html')

def logout(request):
	request.session.flush()
	return redirect(request.META.get('HTTP_REFERER','/'))


def receive(request):
	if request.session.get('login_id'):
		user=request.session.get('login_id')
	else:
		return HttpResponse('上传文件请先登录!')
	if request.method == 'POST':# 获取对象
		if request.POST.get('passwd') != password:
			return HttpResponse('密码不正确,取消上传!')
		obj = request.FILES.get('file')
		import os
		# 上传文件的文件名
		output_name =os.path.join(os.getcwd(),'upload',obj.name)
		if not os.path.exists(os.path.dirname(output_name)):
			os.makedirs(os.path.dirname(output_name))
		f = open(output_name,'wb')
		for chunk in obj.chunks():
			f.write(chunk)
		f.close()
		return  HttpResponse('上传成功.<br><br>' + output_name)
	return render(request, 'upload.html',{'user':user})

provide_path ='/root/file_up_down'
def send(request):
	import os
	org_path=os.path.abspath(request.path)
	path_prev = os.path.abspath(os.path.join(org_path,'..'))
	path = org_path.replace('/download','')
	if path =='':
		path='/'

	if request.session.get('login_id'):
		user=request.session.get('login_id')
		loged_in=True
	else:
		user=''
		loged_in=False
	if os.path.isfile(provide_path+path):
		if not loged_in:
			return HttpResponse('下载文件请先登录!')
		from django.http import FileResponse
		file=open(provide_path+path,'rb')
		response=FileResponse(file)
		response['Content-Type']='application/octet-stream'
		response['Content-Disposition']='attachment;filename="{}"'.format(os.path.basename(path))
		return response
	else:
		if os.path.exists(provide_path+path):
			import datetime
			for dir,sub_dir,file_name in os.walk(provide_path+path):
				dirs_name =sorted(sub_dir)
				files_name=sorted(file_name)
				break
			len_name=50
			len_modify=19
			len_size=20
			dirs =[]
			for a in dirs_name:
				d1 =len_name - len(a)
				if d1 <=0:
					d1 =1
				d2 = datetime.datetime.utcfromtimestamp(os.path.getmtime(provide_path+path+'/'+a)).strftime('%Y-%m-%d %H:%M:%S')
				xxx =' '*d1 + d2 + ' '*(len_size-1) + '-'
				templist=[a,xxx]
				dirs.append(templist)

			files =[]
			for b in files_name:
				f1 = len_name - len(b)
				if f1 <= 0:
					f1 =1
				f2 = datetime.datetime.utcfromtimestamp(os.path.getmtime(provide_path+path+'/'+b)).strftime('%Y-%m-%d %H:%M:%S')
				f3 = os.path.getsize(provide_path+path+'/'+b)
				f3_len = len_size - len(str(f3))
				if f3_len <= 0:
					f3_len = 1
				yyy =' '*f1 + f2 + ' '*f3_len + str(f3)
				templist=[b,yyy]
				files.append(templist)
				


			context={'org_path':org_path,'path':path,
					'path_prev':path_prev,'dirs':dirs,
					'files':files,'user':user,'loged_in':loged_in
					}
			return render(request,'download.html',context)
		else:
			return HttpResponse('page not found '+provide_path+path)

app/templates/download.html
<html>
<head>
	<title>文件传输</title>
</head>
<body bgcolor="white">
<div class="text clearfix" style="text-align:right">
	{%if loged_in%}
		欢迎您,{{user}}. <a href="/logout">退出登录</a>
	{%else%}
		匿名用户, <a href="/login">请登录</a>
	{%endif%}
</div>
<h1>Index of {{path}}</h1>
<hr>
<pre>
<a href="{{path_prev}}">..</a>{%for a in dirs%}
<a href="{{org_path}}/{{a.0}}">{{a.0}}</a>{{a.1}}{%endfor%}
{%for b in files%}
<a href="{{org_path}}/{{b.0}}">{{b.0}}</a>{{b.1}}{%endfor%}

</pre>
<hr>
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<title>文件传输</title>
</head>
<body>
<div class="text clearfix" style="text-align:right">
	{%if loged_in%}
		欢迎您,{{user}}. <a href="/logout">退出登录</a>
	{%else%}
		匿名用户, <a href="/login">请登录</a>
	{%endif%}
</div>
<center>
	<h1>文件传输系统</h1>
    <p><a href="upload/">上传文件</a></p>
    <p><a href="download/">下载文件</a></p>
</center>
</body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html>
<head>
	<title>登录</title>
</head>
<body>
<center><h1>登录账号</h1>
	<form action="" method="post" enctype="multipart/form-data">
    	{% csrf_token %}
    	<p>
    		<label for="id_user">账号:</label>
    		<input type="text" name="user" id="id_user" required="">
    	</p>
    	<p>
    		<label for="id_passwd">密码:</label>
    		<input type="password" name="password" id="id_passwd" maxlength="20" placeholder="请输入密码" required="">
    	</p>
    	<input type="submit" value="提交" >
    </form>
</center>
</body>
</html>

app/templates/upload.html
<!DOCTYPE html>
<html>
<head>
	<title>上传文件</title>
</head>
<body>
<div class="text clearfix" style="text-align:right">
    欢迎您,{{user}}. <a href="/logout">退出登录</a>
</div>
<h1>上传文件</h1>
    <form action="" method="post" enctype="multipart/form-data">
    	{% csrf_token %}
    	<p>
    		<label for="id_file">文件:</label>
    		<input type="file" name="file" id="id_file" required="">
    	</p>
    	<input type="submit" value="提交" >
    </form>
<br>
<br>
<a href="../">返回</a>
</body>
</html>